package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1



/**
 * Apuesta generated by hbm2java
 */
public class Apuesta  implements java.io.Serializable {


     private Integer idApuesta;
     private Catalogo catalogo;
     private Usuario usuario;
     private Float valorApuesta;
     private String marcador;
     private String ganador;

    public Apuesta() {
    }

    public Apuesta(Catalogo catalogo, Usuario usuario, Float valorApuesta, String marcador, String ganador) {
       this.catalogo = catalogo;
       this.usuario = usuario;
       this.valorApuesta = valorApuesta;
       this.marcador = marcador;
       this.ganador = ganador;
    }
   
    public Integer getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(Integer idApuesta) {
        this.idApuesta = idApuesta;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Float getValorApuesta() {
        return this.valorApuesta;
    }
    
    public void setValorApuesta(Float valorApuesta) {
        this.valorApuesta = valorApuesta;
    }
    public String getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(String marcador) {
        this.marcador = marcador;
    }
    public String getGanador() {
        return this.ganador;
    }
    
    public void setGanador(String ganador) {
        this.ganador = ganador;
    }




}


