package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1



/**
 * Boleteria generated by hbm2java
 */
public class Boleteria  implements java.io.Serializable {


     private Integer idboleteria;
     private Catalogo catalogo;
     private Usuario usuario;

    public Boleteria() {
    }

    public Boleteria(Catalogo catalogo, Usuario usuario) {
       this.catalogo = catalogo;
       this.usuario = usuario;
    }
   
    public Integer getIdboleteria() {
        return this.idboleteria;
    }
    
    public void setIdboleteria(Integer idboleteria) {
        this.idboleteria = idboleteria;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


