package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catalogo generated by hbm2java
 */
public class Catalogo  implements java.io.Serializable {


     private Integer idCatalogo;
     private Torneo torneoByCodEquipo1;
     private Torneo torneoByCodEquipo2;
     private Date fechaIn;
     private Date fechaFn;
     private Float entrada;
     private Set<Apuesta> apuestas = new HashSet<Apuesta>(0);
     private Set<Boleteria> boleterias = new HashSet<Boleteria>(0);

    public Catalogo() {
    }

    public Catalogo(Torneo torneoByCodEquipo1, Torneo torneoByCodEquipo2, Date fechaIn, Date fechaFn, Float entrada, Set<Apuesta> apuestas, Set<Boleteria> boleterias) {
       this.torneoByCodEquipo1 = torneoByCodEquipo1;
       this.torneoByCodEquipo2 = torneoByCodEquipo2;
       this.fechaIn = fechaIn;
       this.fechaFn = fechaFn;
       this.entrada = entrada;
       this.apuestas = apuestas;
       this.boleterias = boleterias;
    }
   
    public Integer getIdCatalogo() {
        return this.idCatalogo;
    }
    
    public void setIdCatalogo(Integer idCatalogo) {
        this.idCatalogo = idCatalogo;
    }
    public Torneo getTorneoByCodEquipo1() {
        return this.torneoByCodEquipo1;
    }
    
    public void setTorneoByCodEquipo1(Torneo torneoByCodEquipo1) {
        this.torneoByCodEquipo1 = torneoByCodEquipo1;
    }
    public Torneo getTorneoByCodEquipo2() {
        return this.torneoByCodEquipo2;
    }
    
    public void setTorneoByCodEquipo2(Torneo torneoByCodEquipo2) {
        this.torneoByCodEquipo2 = torneoByCodEquipo2;
    }
    public Date getFechaIn() {
        return this.fechaIn;
    }
    
    public void setFechaIn(Date fechaIn) {
        this.fechaIn = fechaIn;
    }
    public Date getFechaFn() {
        return this.fechaFn;
    }
    
    public void setFechaFn(Date fechaFn) {
        this.fechaFn = fechaFn;
    }
    public Float getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Float entrada) {
        this.entrada = entrada;
    }
    public Set<Apuesta> getApuestas() {
        return this.apuestas;
    }
    
    public void setApuestas(Set<Apuesta> apuestas) {
        this.apuestas = apuestas;
    }
    public Set<Boleteria> getBoleterias() {
        return this.boleterias;
    }
    
    public void setBoleterias(Set<Boleteria> boleterias) {
        this.boleterias = boleterias;
    }




}


