package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Deporte generated by hbm2java
 */
public class Deporte  implements java.io.Serializable {


     private Integer idDeporte;
     private String nombreDeporte;
     private Set<Torneo> torneos = new HashSet<Torneo>(0);

    public Deporte() {
    }

    public Deporte(String nombreDeporte, Set<Torneo> torneos) {
       this.nombreDeporte = nombreDeporte;
       this.torneos = torneos;
    }
   
    public Integer getIdDeporte() {
        return this.idDeporte;
    }
    
    public void setIdDeporte(Integer idDeporte) {
        this.idDeporte = idDeporte;
    }
    public String getNombreDeporte() {
        return this.nombreDeporte;
    }
    
    public void setNombreDeporte(String nombreDeporte) {
        this.nombreDeporte = nombreDeporte;
    }
    public Set<Torneo> getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Set<Torneo> torneos) {
        this.torneos = torneos;
    }




}


