package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1



/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer idJugador;
     private Equipo equipo;
     private String nombreJugador;
     private Integer numeroJugador;

    public Jugador() {
    }

    public Jugador(Equipo equipo, String nombreJugador, Integer numeroJugador) {
       this.equipo = equipo;
       this.nombreJugador = nombreJugador;
       this.numeroJugador = numeroJugador;
    }
   
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombreJugador() {
        return this.nombreJugador;
    }
    
    public void setNombreJugador(String nombreJugador) {
        this.nombreJugador = nombreJugador;
    }
    public Integer getNumeroJugador() {
        return this.numeroJugador;
    }
    
    public void setNumeroJugador(Integer numeroJugador) {
        this.numeroJugador = numeroJugador;
    }




}


