package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private Integer idTorneo;
     private Deporte deporte;
     private String nombreTorneo;
     private Date fechaTorneoIn;
     private Date fechaTorneoOu;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);
     private Set<Catalogo> catalogosForCodEquipo1 = new HashSet<Catalogo>(0);
     private Set<Catalogo> catalogosForCodEquipo2 = new HashSet<Catalogo>(0);

    public Torneo() {
    }

    public Torneo(Deporte deporte, String nombreTorneo, Date fechaTorneoIn, Date fechaTorneoOu, Set<Equipo> equipos, Set<Catalogo> catalogosForCodEquipo1, Set<Catalogo> catalogosForCodEquipo2) {
       this.deporte = deporte;
       this.nombreTorneo = nombreTorneo;
       this.fechaTorneoIn = fechaTorneoIn;
       this.fechaTorneoOu = fechaTorneoOu;
       this.equipos = equipos;
       this.catalogosForCodEquipo1 = catalogosForCodEquipo1;
       this.catalogosForCodEquipo2 = catalogosForCodEquipo2;
    }
   
    public Integer getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(Integer idTorneo) {
        this.idTorneo = idTorneo;
    }
    public Deporte getDeporte() {
        return this.deporte;
    }
    
    public void setDeporte(Deporte deporte) {
        this.deporte = deporte;
    }
    public String getNombreTorneo() {
        return this.nombreTorneo;
    }
    
    public void setNombreTorneo(String nombreTorneo) {
        this.nombreTorneo = nombreTorneo;
    }
    public Date getFechaTorneoIn() {
        return this.fechaTorneoIn;
    }
    
    public void setFechaTorneoIn(Date fechaTorneoIn) {
        this.fechaTorneoIn = fechaTorneoIn;
    }
    public Date getFechaTorneoOu() {
        return this.fechaTorneoOu;
    }
    
    public void setFechaTorneoOu(Date fechaTorneoOu) {
        this.fechaTorneoOu = fechaTorneoOu;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }
    public Set<Catalogo> getCatalogosForCodEquipo1() {
        return this.catalogosForCodEquipo1;
    }
    
    public void setCatalogosForCodEquipo1(Set<Catalogo> catalogosForCodEquipo1) {
        this.catalogosForCodEquipo1 = catalogosForCodEquipo1;
    }
    public Set<Catalogo> getCatalogosForCodEquipo2() {
        return this.catalogosForCodEquipo2;
    }
    
    public void setCatalogosForCodEquipo2(Set<Catalogo> catalogosForCodEquipo2) {
        this.catalogosForCodEquipo2 = catalogosForCodEquipo2;
    }




}


