package co.edu.uniminuto.arqSW.unimonito.hibernate;
// Generated 18/03/2019 04:03:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Roles roles;
     private String nombreUsuario;
     private Integer cedulaUsuario;
     private String correoUsuario;
     private String passUsuario;
     private Set<Boleteria> boleterias = new HashSet<Boleteria>(0);
     private Set<Apuesta> apuestas = new HashSet<Apuesta>(0);

    public Usuario() {
    }

    public Usuario(Roles roles, String nombreUsuario, Integer cedulaUsuario, String correoUsuario, String passUsuario, Set<Boleteria> boleterias, Set<Apuesta> apuestas) {
       this.roles = roles;
       this.nombreUsuario = nombreUsuario;
       this.cedulaUsuario = cedulaUsuario;
       this.correoUsuario = correoUsuario;
       this.passUsuario = passUsuario;
       this.boleterias = boleterias;
       this.apuestas = apuestas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Integer getCedulaUsuario() {
        return this.cedulaUsuario;
    }
    
    public void setCedulaUsuario(Integer cedulaUsuario) {
        this.cedulaUsuario = cedulaUsuario;
    }
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }
    public Set<Boleteria> getBoleterias() {
        return this.boleterias;
    }
    
    public void setBoleterias(Set<Boleteria> boleterias) {
        this.boleterias = boleterias;
    }
    public Set<Apuesta> getApuestas() {
        return this.apuestas;
    }
    
    public void setApuestas(Set<Apuesta> apuestas) {
        this.apuestas = apuestas;
    }




}


