package co.edu.uniminuto.arqSW.hibernate;
// Generated 20/03/2019 11:53:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Apuesta generated by hbm2java
 */
@Entity
@Table(name="Apuesta"
    ,catalog="unimonito"
)
public class Apuesta  implements java.io.Serializable {


     private Integer idApuesta;
     private Catalogo catalogo;
     private Usuario usuario;
     private Float valorApuesta;
     private String marcador;
     private String ganador;

    public Apuesta() {
    }

    public Apuesta(Catalogo catalogo, Usuario usuario, Float valorApuesta, String marcador, String ganador) {
       this.catalogo = catalogo;
       this.usuario = usuario;
       this.valorApuesta = valorApuesta;
       this.marcador = marcador;
       this.ganador = ganador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idApuesta", unique=true, nullable=false)
    public Integer getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(Integer idApuesta) {
        this.idApuesta = idApuesta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_Catalogo")
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_Usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="ValorApuesta", precision=12, scale=0)
    public Float getValorApuesta() {
        return this.valorApuesta;
    }
    
    public void setValorApuesta(Float valorApuesta) {
        this.valorApuesta = valorApuesta;
    }

    
    @Column(name="marcador", length=45)
    public String getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(String marcador) {
        this.marcador = marcador;
    }

    
    @Column(name="ganador", length=45)
    public String getGanador() {
        return this.ganador;
    }
    
    public void setGanador(String ganador) {
        this.ganador = ganador;
    }




}


