package co.edu.uniminuto.arqSW.hibernate;
// Generated 20/03/2019 11:53:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Boleteria generated by hbm2java
 */
@Entity
@Table(name="boleteria"
    ,catalog="unimonito"
)
public class Boleteria  implements java.io.Serializable {


     private Integer idboleteria;
     private Catalogo catalogo;
     private Usuario usuario;

    public Boleteria() {
    }

    public Boleteria(Catalogo catalogo, Usuario usuario) {
       this.catalogo = catalogo;
       this.usuario = usuario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idboleteria", unique=true, nullable=false)
    public Integer getIdboleteria() {
        return this.idboleteria;
    }
    
    public void setIdboleteria(Integer idboleteria) {
        this.idboleteria = idboleteria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_catalogo")
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_Usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


