package co.edu.uniminuto.arqSW.hibernate;
// Generated 20/03/2019 11:53:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name="Equipo"
    ,catalog="unimonito"
)
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Torneo torneo;
     private String nombreEquipo;
     private Set<Catalogo> catalogosForCodEquipo2 = new HashSet<Catalogo>(0);
     private Set<Catalogo> catalogosForCodEquipo1 = new HashSet<Catalogo>(0);
     private Set<Jugador> jugadors = new HashSet<Jugador>(0);

    public Equipo() {
    }

    public Equipo(Torneo torneo, String nombreEquipo, Set<Catalogo> catalogosForCodEquipo2, Set<Catalogo> catalogosForCodEquipo1, Set<Jugador> jugadors) {
       this.torneo = torneo;
       this.nombreEquipo = nombreEquipo;
       this.catalogosForCodEquipo2 = catalogosForCodEquipo2;
       this.catalogosForCodEquipo1 = catalogosForCodEquipo1;
       this.jugadors = jugadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEquipo", unique=true, nullable=false)
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_Torneo")
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }

    
    @Column(name="NombreEquipo", length=45)
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipoByCodEquipo2")
    public Set<Catalogo> getCatalogosForCodEquipo2() {
        return this.catalogosForCodEquipo2;
    }
    
    public void setCatalogosForCodEquipo2(Set<Catalogo> catalogosForCodEquipo2) {
        this.catalogosForCodEquipo2 = catalogosForCodEquipo2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipoByCodEquipo1")
    public Set<Catalogo> getCatalogosForCodEquipo1() {
        return this.catalogosForCodEquipo1;
    }
    
    public void setCatalogosForCodEquipo1(Set<Catalogo> catalogosForCodEquipo1) {
        this.catalogosForCodEquipo1 = catalogosForCodEquipo1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipo")
    public Set<Jugador> getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set<Jugador> jugadors) {
        this.jugadors = jugadors;
    }




}


