package co.edu.uniminuto.arqSW.hibernate;
// Generated 20/03/2019 11:53:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name="Jugador"
    ,catalog="unimonito"
)
public class Jugador  implements java.io.Serializable {


     private Integer idJugador;
     private Equipo equipo;
     private String nombreJugador;
     private Integer numeroJugador;

    public Jugador() {
    }

    public Jugador(Equipo equipo, String nombreJugador, Integer numeroJugador) {
       this.equipo = equipo;
       this.nombreJugador = nombreJugador;
       this.numeroJugador = numeroJugador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idJugador", unique=true, nullable=false)
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_Equipo")
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }

    
    @Column(name="NombreJugador", length=45)
    public String getNombreJugador() {
        return this.nombreJugador;
    }
    
    public void setNombreJugador(String nombreJugador) {
        this.nombreJugador = nombreJugador;
    }

    
    @Column(name="NumeroJugador")
    public Integer getNumeroJugador() {
        return this.numeroJugador;
    }
    
    public void setNumeroJugador(Integer numeroJugador) {
        this.numeroJugador = numeroJugador;
    }




}


