package co.edu.uniminuto.arqSW.hibernate;
// Generated 20/03/2019 11:53:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="Torneo"
    ,catalog="unimonito"
)
public class Torneo  implements java.io.Serializable {


     private Integer idTorneo;
     private Deporte deporte;
     private String nombreTorneo;
     private Date fechaTorneoIn;
     private Date fechaTorneoOu;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Torneo() {
    }

    public Torneo(Deporte deporte, String nombreTorneo, Date fechaTorneoIn, Date fechaTorneoOu, Set<Equipo> equipos) {
       this.deporte = deporte;
       this.nombreTorneo = nombreTorneo;
       this.fechaTorneoIn = fechaTorneoIn;
       this.fechaTorneoOu = fechaTorneoOu;
       this.equipos = equipos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTorneo", unique=true, nullable=false)
    public Integer getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(Integer idTorneo) {
        this.idTorneo = idTorneo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_Deporte")
    public Deporte getDeporte() {
        return this.deporte;
    }
    
    public void setDeporte(Deporte deporte) {
        this.deporte = deporte;
    }

    
    @Column(name="nombreTorneo", length=45)
    public String getNombreTorneo() {
        return this.nombreTorneo;
    }
    
    public void setNombreTorneo(String nombreTorneo) {
        this.nombreTorneo = nombreTorneo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaTorneoIn", length=10)
    public Date getFechaTorneoIn() {
        return this.fechaTorneoIn;
    }
    
    public void setFechaTorneoIn(Date fechaTorneoIn) {
        this.fechaTorneoIn = fechaTorneoIn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaTorneoOu", length=10)
    public Date getFechaTorneoOu() {
        return this.fechaTorneoOu;
    }
    
    public void setFechaTorneoOu(Date fechaTorneoOu) {
        this.fechaTorneoOu = fechaTorneoOu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


